algoritmo "area_retangulo"
// Função :  calcula a area do retangulo
// Autor : Felipe Barbosa dos Santos
// Data : 23/03/2023
// Seção de Declarações 
var
    lado, altura, area: inteiro
inicio
// Seção de Comandos
   escreva("Informe o valor do lado: ")
   leia(lado)
   escreva("Informe o valor da altura: ")
   leia(altura)
   area <- lado * altura
   
   escreval("O valor da area do retângulo é: ", area)
fimalgoritmo
